apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/kjwilde-hotmail-com/lightning-node-easy:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/kjwilde-hotmail-com/lightning-node-easy:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: lightning-node-easy
        chartPath: charts/lightning-node-easy
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/kjwilde-hotmail-com/lightning-node-easy"
          image.tag: "{{.DIGEST_HEX}}"
